name: CI

on:
  push:
  pull_request:

jobs:
  checks:
    name: Validate & PHPCS availability
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: composer:v2
          coverage: none
      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist --ansi
      - name: Composer validate
        run: composer validate --no-check-lock --ansi
      - name: Lint PHP
        run: |
          find . -path './vendor' -prune -o -name '*.php' -print0 | xargs -0 -n1 php -l
      - name: List installed standards
        run: vendor/bin/phpcs -i
